spring:
  profiles:
    default: local
  mail:
    username: ssafy.recodeli@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    password: odhzjtjonepisuqm
    port: '587'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-secret: sOfXzlb5VqZ53F8fXBE093VaGqxQ3QJM
            authorization-grant-type: authorization_code
            client-id: 5198c023eb72403d4f51b7b007cef5e3
            scope: profile_nickname,account_email
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/oauth2/code/{registrationId}
            client-name: Kakao
          naver:
            client-id: aXsmLMcjsQENHcuX_ANv
            client-name: Naver
            redirect-uri: http://localhost:8080/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            scope: email,nickname
            client-secret: fV4mRVk2_5
          google:
            client-id: 673256025189-gfisd4bv96rbcf20ruio1l9k8odf053d.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/oauth2/code/{registrationId}
            scope: email,profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
  datasource:
    hikari:
      idle-timeout: '600000'
      connection-init-sql: SELECT 1
      validation-timeout: '2000'
      maximum-pool-size: '10'
      auto-commit: 'true'
      connection-timeout: '5000'
      max-lifetime: '1800000'
      minimum-idle: '10'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: 'false'
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: SeC51aWtGJk235jGHw412agHsGQ2asdfaw25asdfaAGAS
logging:
  level:
    root: info
    com:
      ssafy:
        recodeli: debug
