spring:
  mail:
    username: ssafy.recodeli@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    password: bljiyyyveuairlmb
    port: '587'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-secret: wKas7eenfnZjKdSnDMMMv0nLwZvCuass
            authorization-grant-type: authorization_code
            client-id: 0018c14a3078270bc96ab118d3b5571a
            scope: profile_nickname,account_email
            client-authentication-method: POST
            redirect-uri: https://togetdog.site/oauth2/code/{registrationId}
            client-name: Kakao
          naver:
            client-id: 7fC7r9ej9wWJa4f_FEb_
            client-name: Naver
            redirect-uri: https://togetdog.site/oauth2/code/{registrationId}
            authorization-grant-type: authorization_code
            scope: email,nickname
            client-secret: yhagYvWP16
          google:
            client-id: 1075413009852-5g0hlfila6rpqtjpnv06b8ispbdorb6e.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://togetdog.site/oauth2/code/{registrationId}
            scope: email,profile
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
          kakao:
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
  datasource:
    hikari:
      idle-timeout: '600000'
      connection-init-sql: SELECT 1
      validation-timeout: '2000'
      maximum-pool-size: '10'
      auto-commit: 'true'
      connection-timeout: '5000'
      max-lifetime: '1800000'
      minimum-idle: '10'
    password: ??a302
    url: jdbc:mysql://43.200.255.205:3333/recodeli?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: unni
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: 'false'
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: SeC51aWtGJk235jGHw412agHsGQ2asdfaw25asdfaAGAS
logging:
  level:
    root: info
    com:
      ssafy:
        recodeli: debug
