spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: http://localhost:8080/oauth2/code/{registrationId}
          naver:
            redirect-uri: http://localhost:8080/oauth2/code/{registrationId}
          google:
            redirect-uri: http://localhost:8080/oauth2/code/{registrationId}
  datasource:
    username: root
    password: ssafy
    url: jdbc:mysql://localhost:3306/recodeli?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create