spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: unni
    password: xmrghka302
    url: jdbc:mysql://3.35.214.235:3333/toonbti?useSSL=true&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
